//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.UKLocation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET", ConfigurationName="UKLocation.UKLocationSoap")]
    public interface UKLocationSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetUKLocationByCounty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUKLocationByCounty(string County);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetUKLocationByCounty", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetUKLocationByCountyAsync(string County);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetUKLocationByTown", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUKLocationByTown(string Town);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetUKLocationByTown", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetUKLocationByTownAsync(string Town);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetUKLocationByPostCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUKLocationByPostCode(string PostCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetUKLocationByPostCode", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetUKLocationByPostCodeAsync(string PostCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/ValidateUKAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ValidateUKAddress(string Town, string County, string PostCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/ValidateUKAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ValidateUKAddressAsync(string Town, string County, string PostCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UKLocationSoapChannel : TestProject.UKLocation.UKLocationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UKLocationSoapClient : System.ServiceModel.ClientBase<TestProject.UKLocation.UKLocationSoap>, TestProject.UKLocation.UKLocationSoap {
        
        public UKLocationSoapClient() {
        }
        
        public UKLocationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UKLocationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UKLocationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UKLocationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetUKLocationByCounty(string County) {
            return base.Channel.GetUKLocationByCounty(County);
        }
        
        public System.Threading.Tasks.Task<string> GetUKLocationByCountyAsync(string County) {
            return base.Channel.GetUKLocationByCountyAsync(County);
        }
        
        public string GetUKLocationByTown(string Town) {
            return base.Channel.GetUKLocationByTown(Town);
        }
        
        public System.Threading.Tasks.Task<string> GetUKLocationByTownAsync(string Town) {
            return base.Channel.GetUKLocationByTownAsync(Town);
        }
        
        public string GetUKLocationByPostCode(string PostCode) {
            return base.Channel.GetUKLocationByPostCode(PostCode);
        }
        
        public System.Threading.Tasks.Task<string> GetUKLocationByPostCodeAsync(string PostCode) {
            return base.Channel.GetUKLocationByPostCodeAsync(PostCode);
        }
        
        public string ValidateUKAddress(string Town, string County, string PostCode) {
            return base.Channel.ValidateUKAddress(Town, County, PostCode);
        }
        
        public System.Threading.Tasks.Task<string> ValidateUKAddressAsync(string Town, string County, string PostCode) {
            return base.Channel.ValidateUKAddressAsync(Town, County, PostCode);
        }
    }
}
